# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Create a preview build artifact from the HEAD of the dev branch.
trigger:
  branches:
    include:
    - dev
    - feature/2.0
  paths:
    include:
      - src/*
    exclude:
      - .github/*
      - build/*
      - docs/*
      - pipelines/*
      - scripts/*
      - .gitignore
      - CONTRIBUTING.md
      - LICENSE.txt
      - Microsoft.Graph.Core.sln
      - README.md
      - THIRD PARTY NOTICES
      - appveyor.yml

pr: none

variables:
  PACKAGE_NAME: 'microsoft.graph.core'
  PROJECT_PATH: '.\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: 6.x

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: 'Run CredScan'
  inputs:
    toolMajorVersion: 'V2'
    scanFolder: '$(Build.SourcesDirectory)'
    debugMode: false

- task: PowerShell@2
  displayName: 'Validate updated version'
  inputs:
    targetType: filePath
    filePath: 'scripts\ValidateUpdatedNugetVersion.ps1'
    arguments: '-packageName "$(PACKAGE_NAME)" -projectPath "$(PROJECT_PATH)"'
  enabled: true

- task: PowerShell@2
  displayName: 'Set or increment preview version.'
  inputs:
    targetType: filePath
    filePath: 'scripts\IncrementPreviewVersion.ps1'
    arguments: '-packageName "$(PACKAGE_NAME)" -projectPath "$(PROJECT_PATH)"'
  enabled: true

- powershell: |
    dotnet workload restore $(Build.SourcesDirectory)\Microsoft.Graph.Core.sln
  displayName: 'dotnet workload restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'run tests'
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)\tests\Microsoft.Graph.DotnetCore.Core.Test\Microsoft.Graph.DotnetCore.Core.Test.csproj'
    arguments: '--configuration Debug --verbosity normal'

- task: PowerShell@2
  displayName: 'Enable signing'
  inputs:
    targetType: filePath
    filePath: 'scripts\EnableSigning.ps1'
    arguments: '-projectPath "$(PROJECT_PATH)"'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(Build.SourcesDirectory)\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj'
    arguments: '-c Release --no-incremental'

- task: EsrpCodeSigning@2
  displayName: 'ESRP DLL Strong Name (Microsoft.Graph.Core)'
  inputs:
    ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet - test'
    FolderPath: src/Microsoft.Graph.Core/bin/release
    Pattern: '**\*Microsoft.Graph.Core.dll'
    signConfigType: inlineSignParams
    UseMinimatch: true
    inlineOperation: |
     [
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameSign",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameVerify",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
    SessionTimeout: 20

- task: EsrpCodeSigning@2
  displayName: 'ESRP DLL CodeSigning (Microsoft.Graph.Core)'
  inputs:
    ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet - test'
    FolderPath: src/Microsoft.Graph.Core/bin/release
    Pattern: '**\*Microsoft.Graph.Core.dll'
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
                 {
                     "parameterName": "OpusName",
                     "parameterValue": "Microsoft"
                 },
                 {
                     "parameterName": "OpusInfo",
                     "parameterValue": "http://www.microsoft.com"
                 },
                 {
                     "parameterName": "FileDigest",
                     "parameterValue": "/fd \"SHA256\""
                 },
                 {
                     "parameterName": "PageHash",
                     "parameterValue": "/NPH"
                 },
                 {
                     "parameterName": "TimeStamp",
                     "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                 }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
    SessionTimeout: 20

# arguments are not parsed in DotNetCoreCLI@2 task for `pack` command, that's why we have a custom pack command here
- powershell: |
    dotnet pack $env:BUILD_SOURCESDIRECTORY/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg --no-build --output $env:BUILD_ARTIFACTSTAGINGDIRECTORY --configuration Release
  displayName: dotnet pack

- task: EsrpCodeSigning@2
  displayName: 'ESRP NuGet CodeSigning'
  inputs:
    ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet - test'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    UseMinimatch: true
    Pattern: '*nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
          [
              {
                  "keyCode": "CP-401405",
                  "operationSetCode": "NuGetSign",
                  "parameters": [ ],
                  "toolName": "sign",
                  "toolVersion": "1.0"
              },
              {
                  "keyCode": "CP-401405",
                  "operationSetCode": "NuGetVerify",
                  "parameters": [ ],
                  "toolName": "sign",
                  "toolVersion": "1.0"
              }
          ]
    SessionTimeout: 20

- task: CopyFiles@2
  displayName: 'Copy release scripts to artifact staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     scripts\GetNugetPackageVersion.ps1
     scripts\GetLatestCommitSHA.ps1
    TargetFolder: '$(Build.ArtifactStagingDirectory) '

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Microsoft.Graph.Core.nupkg and release pipeline scripts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: PreviewReleaseArtifact

